drop table if exists member CASCADE;
create table member
(
    id   bigint generated by default as identity,
    name varchar(255),
    primary key (id)
);
--  INSERT INTO MEMBER (ID,NAME) VALUES ( 1 , 'jpppa' );
--  INSERT INTO MEMBER (ID,NAME) VALUES ( 2 , 'java' );
--  INSERT INTO MEMBER (ID,NAME) VALUES ( 2 , 'jaxx' );

